esm-user-login-demo: using TypeScript and ES6
esridevsummit/arcgis-authentication pull request #6
Opened 2022-11-23 13:55 UTC by esride-nik

2022-11-23 17:13 UTC, jf990 requested changes
Can you also include an update to the README to change http://localhost:3000 to https://locahost:3000 the oauth callback didn't work for me until I changed that in my app registration

2022-11-23 17:13 UTC, jf990 commented on esm-user-login-demo/index.ts
> +    // reponse of type __esri.DirectionsLastRoute
```suggestion
    // response of type __esri.DirectionsLastRoute
```

2022-11-23 17:13 UTC, jf990 commented on esm-user-login-demo/index.js
> +        // reponse of type __esri.DirectionsLastRoute
```suggestion
        // response of type __esri.DirectionsLastRoute
```

2023-01-19 10:45 UTC, esride-nik commented on esm-user-login-demo/index.js
> +        // reponse of type __esri.DirectionsLastRoute
Sure! Sorry I didn't see your comments before 🙈 need to work on my collaboration skills.

2023-01-24 01:30 UTC, jf990 approved these changes
i ran this branch locally and everything worked as expected. thanks!

2023-01-24 01:30 UTC, merged